import type { ContentGenerationInput } from "@/types/content-generation-input";
import type { GeneratedContent, GeneratedPostContent } from "@/types/generated-content";
import { buildGenerationContext } from "@/engine/generation-context-builder";
import { generateCta } from "@/engine/cta-generator";
import { generateHashtags } from "@/engine/hashtag-engine";
import { generateVisualDirection } from "@/engine/visual-direction-engine";
import { checkContentQuality } from "@/engine/content-quality-engine";
import type { ContentGenerationProvider } from "./content-generation-provider";

const hookSets: Record<string, string[]> = { Jewellery: ["Some moments deserve more than words.", "What makes a piece become an heirloom?", "Craftsmanship is the detail you feel."], "Real Estate": ["More than a home. A smarter investment.", "What would better living look like?", "A better address changes the everyday."], Perfume: ["Not just a fragrance. A feeling that stays.", "What mood will you leave behind?", "Some memories begin with a single note."], "FMCG / Food": ["One bite. One familiar feeling.", "What makes a daily moment worth sharing?", "Good food makes room for connection."] };
export class MockContentGenerationProvider implements ContentGenerationProvider { async generateContent(input: ContentGenerationInput, variation = 0): Promise<GeneratedPostContent> { const context = buildGenerationContext(input); const name = context.brandName ?? context.industry.name; const hooks = hookSets[context.industry.name] ?? hookSets["FMCG / Food"]; const hook = hooks[variation % hooks.length]; const product = input.brandContext?.products?.[0] ?? context.contentPillar; const value = input.brandContext?.uniqueSellingPoints?.[0] ?? context.industry.focusAreas[0]; const caption = `${hook}\n\n${context.contentTheme} comes to life through ${context.contentPillar.toLowerCase()}. Discover how ${product.toLowerCase()} brings ${value.toLowerCase()} into a moment designed for ${context.targetAudience?.toLowerCase() ?? "people who value thoughtful choices"}.\n\n${name} brings a distinct point of view to every detail, with ${context.communicationTone.slice(0, 2).join(" and ").toLowerCase()} at the centre.`; const content: GeneratedPostContent = { title: `${context.contentTheme}: ${context.contentPillar}`, hook, caption, callToAction: generateCta(input), hashtags: generateHashtags(input), visualDirection: generateVisualDirection(input) }; return content; } }
export function createGeneratedContent(input: ContentGenerationInput, content: GeneratedPostContent): GeneratedContent { const context = buildGenerationContext(input); const now = new Date().toISOString(); return { id: `generated-${input.calendarPost.id}`, projectId: input.project.id, calendarPostId: input.calendarPost.id, postNumber: input.calendarPost.postNumber, status: "READY", content, generationContext: context, qualityReport: checkContentQuality(content, context), createdAt: now, updatedAt: now }; }
export const contentGenerationService = new MockContentGenerationProvider();