"use client";
import { AnimatePresence, motion } from "framer-motion";
import { Sparkles } from "lucide-react";
import type { ContentConfiguration } from "@/types/content-configuration";
import type { IndustryConfig } from "@/types/industry";
import { contentGoals } from "@/config/content-goals";
import { contentFormats } from "@/config/content-formats";
import { audiences } from "@/config/audiences";
import { durationLabels, getPlanInsight } from "@/lib/content-configuration";
import { tonePreferences } from "@/config/tones";

export function StrategySummary({ configuration, industry }: { configuration: ContentConfiguration; industry: IndustryConfig }) { const goal = contentGoals.find((item) => item.id === configuration.primaryGoal)?.name; const audience = audiences.find((item) => item.id === configuration.targetAudience)?.name; const formats = configuration.contentFormats.map((id) => contentFormats.find((item) => item.id === id)?.name).filter(Boolean); const tones = configuration.tonePreferences.map((id) => tonePreferences.find((item) => item.id === id)?.name).filter(Boolean); const insight = getPlanInsight(configuration); return <aside className="h-fit rounded-xl bg-[#222149] p-6 text-white lg:sticky lg:top-6"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-violet-200"><Sparkles size={14} /> Strategy Preview</div><p className="mt-2 text-xs leading-5 text-white/45">Live view of the strategy you&apos;re designing.</p><div className="mt-7 space-y-5"><SummaryItem label="Industry" value={industry.name} /><SummaryItem label="Content duration" value={durationLabels[configuration.duration]} /><SummaryItem label="Content volume" value={`${configuration.postCount} Posts${configuration.isCustomPostCount ? " · Custom" : ""}`} /><SummaryItem label="Primary goal" value={goal ?? "Choose a goal"} muted={!goal} /><SummaryItem label="Selected formats" value={formats.length ? formats.join(" · ") : "Choose formats"} muted={!formats.length} /><SummaryItem label="Target audience" value={configuration.targetAudience === "CUSTOM_AUDIENCE" && configuration.customAudience ? configuration.customAudience : audience ?? "Choose an audience"} muted={!audience && !configuration.customAudience} /></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-[10px] uppercase tracking-widest text-white/40">Communication style</p><div className="mt-3"><p className="text-[10px] text-white/40">Industry DNA</p><div className="mt-2 flex flex-wrap gap-1.5">{industry.tone.map((tone) => <span key={tone} className="rounded bg-white/10 px-2 py-1 text-[11px] text-white/75">{tone}</span>)}</div></div><AnimatePresence mode="popLayout"><motion.div key={tones.join("-")} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} className="mt-4"><p className="text-[10px] text-white/40">Additional preferences</p><p className="mt-2 text-xs text-white/75">{tones.length ? tones.join(" · ") : "Optional"}</p></motion.div></AnimatePresence></div><div className="mt-6 rounded-lg bg-white/10 p-4"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-widest text-violet-200">Content plan insight</p><span className="rounded-full bg-emerald-300/15 px-2 py-1 text-[9px] font-medium text-emerald-200">{insight.level}</span></div><p className="mt-2 text-xs leading-5 text-white/70">This is a {insight.text.toLowerCase()}.</p></div></aside>; }
function SummaryItem({ label, value, muted }: { label: string; value: string; muted?: boolean }) { return <div><p className="text-[10px] uppercase tracking-widest text-white/40">{label}</p><p className={`mt-1 text-sm ${muted ? "text-white/35" : "text-white/85"}`}>{value}</p></div>; }