export const demoContentStrategy = {
  id: "demo-strategy-aurora",
  projectId: "demo-project-aurora",
  strategyName: "Aurora Atelier Storytelling Strategy",
  strategySummary: "Position Aurora Atelier as a contemporary luxury jewellery house rooted in craftsmanship and personal meaning.",
  brandPositioning: "Luxury jewellery shaped by heritage, modern elegance, and emotional significance.",
  targetAudienceProfile: {
    summary: "Luxury-minded buyers who value thoughtful gifting, craftsmanship, and expressive design.",
    primaryAudience: "Affluent millennial and Gen X buyers",
    audienceMotivations: ["Meaningful gifting", "Atelier craftsmanship", "Personal symbolism"],
    audienceInterests: ["Luxury fashion", "Modern heirlooms", "Design curation"],
    audienceNeeds: ["Trust", "Design clarity", "Premium storytelling"],
  },
  communicationStyle: {
    primaryTone: ["elevated", "warm", "confident"],
    vocabularyGuidelines: ["crafted", "timeless", "carefully made"],
    messagingStyle: ["story-first", "premium but accessible", "considered"],
    avoid: ["hard-sell", "overly technical", "mass-market language"],
  },
  primaryObjective: "Build brand desire and product discovery",
  secondaryObjectives: ["Increase engagement", "Drive direct consideration", "Elevate brand perception"],
  contentPillars: [
    { id: "craftsmanship", title: "Craftsmanship", description: "Show the human detail behind each piece.", objective: "Create trust and admiration", industryFocus: ["Jewellery", "Luxury"], percentage: 32, postCount: 3, recommendedFormats: ["INSTAGRAM_POST", "STORYTELLING"] },
    { id: "product-story", title: "Product Story", description: "Introduce signature silhouettes and gifting moments.", objective: "Drive product discovery", industryFocus: ["Products", "Lifestyle"], percentage: 28, postCount: 3, recommendedFormats: ["PRODUCT_HIGHLIGHT", "INSTAGRAM_POST"] },
    { id: "education", title: "Education", description: "Explain materials, value, and design intent.", objective: "Increase informed buying confidence", industryFocus: ["Luxury", "Shopping"], percentage: 20, postCount: 2, recommendedFormats: ["STORYTELLING", "CAROUSEL"] },
    { id: "lifestyle", title: "Lifestyle", description: "Show the object in intimate everyday rituals.", objective: "Create emotional association", industryFocus: ["Lifestyle", "Luxury"], percentage: 20, postCount: 2, recommendedFormats: ["INSTAGRAM_POST", "REEL"] },
  ],
  contentMix: [{ contentType: "Story-led product posts", percentage: 40, postCount: 4, purpose: "Drive emotional connection" }],
  publishingPlan: {
    duration: "4 weeks",
    totalPosts: 10,
    postsPerWeek: 2,
    recommendedDays: ["Tuesday", "Friday"],
    frequencyLabel: "RECOMMENDED",
    strategyNotes: ["Lead with craftsmanship and emotional storytelling."],
  },
  calendarBlueprint: {
    posts: [
      { id: "post-1", postNumber: 1, weekNumber: 1, suggestedDay: "Tuesday", contentPillarId: "craftsmanship", contentTheme: "Origin story", objective: "Introduce the atelier", recommendedFormat: "INSTAGRAM_POST" },
      { id: "post-2", postNumber: 2, weekNumber: 1, suggestedDay: "Friday", contentPillarId: "product-story", contentTheme: "Signature ring", objective: "Feature the hero product", recommendedFormat: "PRODUCT_HIGHLIGHT" },
      { id: "post-3", postNumber: 3, weekNumber: 2, suggestedDay: "Tuesday", contentPillarId: "education", contentTheme: "Materials matter", objective: "Explain craftsmanship", recommendedFormat: "STORYTELLING" },
      { id: "post-4", postNumber: 4, weekNumber: 2, suggestedDay: "Friday", contentPillarId: "lifestyle", contentTheme: "Everyday ritual", objective: "Tie product to lifestyle", recommendedFormat: "INSTAGRAM_POST" },
      { id: "post-5", postNumber: 5, weekNumber: 3, suggestedDay: "Tuesday", contentPillarId: "craftsmanship", contentTheme: "The making process", objective: "Show process and care", recommendedFormat: "STORYTELLING" },
      { id: "post-6", postNumber: 6, weekNumber: 3, suggestedDay: "Friday", contentPillarId: "product-story", contentTheme: "Pearl moment", objective: "Highlight a seasonal hero", recommendedFormat: "PRODUCT_HIGHLIGHT" },
      { id: "post-7", postNumber: 7, weekNumber: 4, suggestedDay: "Tuesday", contentPillarId: "education", contentTheme: "Design journal", objective: "Share brand values", recommendedFormat: "CAROUSEL" },
      { id: "post-8", postNumber: 8, weekNumber: 4, suggestedDay: "Friday", contentPillarId: "lifestyle", contentTheme: "Gifted with intention", objective: "Create an emotional CTA", recommendedFormat: "INSTAGRAM_POST" },
    ],
  },
  createdAt: "2026-09-01T00:00:00.000Z",
  updatedAt: "2026-09-01T00:00:00.000Z",
};
