export const demoGeneratedContent = [
  {
    id: "demo-generated-1",
    projectId: "demo-project-aurora",
    calendarPostId: "post-1",
    postNumber: 1,
    status: "READY",
    content: {
      title: "Modern heirloom pieces, designed to be worn forever",
      hook: "Not just jewellery. A story you carry with you.",
      caption: "Each Aurora Atelier piece is shaped with intention, blending heritage craft with modern design to make every detail feel personal and enduring.",
      callToAction: "Discover the collection",
      hashtags: ["#AuroraAtelier", "#ModernHeirloom", "#FineJewellery"],
      visualDirection: {
        concept: "Timeless jewellery portrait with soft studio light",
        mood: ["elevated", "intimate", "luxury"],
        composition: "Close-up product still with elegant negative space",
        subjectFocus: "Signature ring and pearls",
        backgroundSuggestion: "Warm ivory and champagne tones",
        typographySuggestion: "Elegant serif, premium editorial",
        colorDirection: ["ivory", "champagne", "gold"],
        imagePrompt: "Luxury fine jewellery campaign editorial portrait",
      },
    },
    generationContext: {
      industry: { id: "LUXURY_JEWELLERY", name: "Luxury Jewellery", description: "Luxury jewellery", contentFormats: [], tone: [] },
      brandName: "Aurora Atelier",
      contentPillar: "Craftsmanship",
      contentTheme: "Origin story",
      objective: "Introduce the atelier",
      recommendedFormat: "INSTAGRAM_POST",
      targetAudience: "Luxury buyers",
      communicationTone: ["elevated", "warm"],
      brandKeywords: ["craftsmanship", "modern luxury"],
      uniqueSellingPoints: ["Heirloom design", "ethical sourcing"],
    },
    generatedImage: {
      id: "demo-image-1",
      projectId: "demo-project-aurora",
      generatedContentId: "demo-generated-1",
      calendarPostId: "post-1",
      status: "READY",
      imageUrl: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=80",
      prompt: {
        prompt: "Luxury jewellery editorial portrait",
        aspectRatio: "4:5",
        visualStyle: "Luxury",
        mood: ["elevated"],
        subject: "Signature ring",
        composition: "Close-up portrait",
      },
      metadata: {
        provider: "Demo",
        generatedAt: "2026-09-01T00:00:00.000Z",
      },
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    },
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];
