"use client";
import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { industries } from "@/config/industries";
import { CreateProjectHeader } from "@/components/create-project/create-project-header";
import { IndustryCard } from "@/components/create-project/industry-card";
import { IndustryDnaPanel } from "@/components/create-project/industry-dna-panel";
import { ProjectStepper } from "@/components/create-project/project-stepper";

export default function CreatePage() { const [selectedId, setSelectedId] = useState(industries[1].id); const [showToast, setShowToast] = useState(false); const selected = industries.find((industry) => industry.id === selectedId) ?? industries[0]; const continueFlow = () => { setShowToast(true); window.setTimeout(() => setShowToast(false), 4200); }; return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><CreateProjectHeader /><ProjectStepper /><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_340px]"><section><div className="mb-6"><h2 className="text-2xl font-semibold tracking-[-.03em]">Choose your industry</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted">Your selected industry will shape the tone, vocabulary, audience, and content strategy.</p></div><div className="grid gap-3 sm:grid-cols-2">{industries.map((industry) => <IndustryCard key={industry.id} industry={industry} selected={selected.id === industry.id} onSelect={() => setSelectedId(industry.id)} />)}</div><div className="mt-6 flex items-center gap-2 rounded-lg border border-dashed border-border p-4 text-xs text-muted"><span className="flex size-6 items-center justify-center rounded-full bg-surface-muted">i</span> Context configuration, strategy, and generation will unlock in the next phases.</div></section><IndustryDnaPanel industry={selected} onContinue={continueFlow} /></div>{showToast && <div role="status" className="fixed bottom-5 left-1/2 z-30 flex -translate-x-1/2 items-center gap-3 rounded-lg bg-[#222149] px-4 py-3 text-sm text-white shadow-2xl"><CheckCircle2 size={17} className="text-emerald-300" /> Industry selected successfully. Context configuration will be available in Phase 2.</div>}</div>; }